"""Cluster administration: kubeadm, etcdctl, PKI/kubeconfig and a container registry.

These are the CKA topics that a workload simulator normally cannot reach. They
are modelled here faithfully enough that the *procedure and its rules* are what
you practise -- which is exactly what the exam and a real upgrade night test:

  kubeadm   version skew rules, control plane first, drain -> upgrade -> uncordon
  etcdctl   the mandatory --endpoints/--cacert/--cert/--key flags, snapshot
            save / status / restore, and restoring into a live cluster
  PKI       CertificateSigningRequest -> approve -> issue -> kubeconfig entry,
            certificate expiry and renewal
  registry  build/tag/push, public vs private images, imagePullSecrets

What is NOT simulated: real machines, real TLS material, real container builds.
Those need kind/minikube and a real Docker daemon -- see README section 6.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import time
from typing import Any, Dict, List, Optional, Tuple

from .cluster_factory import add_node
from .model import Cluster, deep_get

# --------------------------------------------------------------------------
# versions
# --------------------------------------------------------------------------
RELEASES = ["1.28.11", "1.29.7", "1.30.2", "1.31.1", "1.32.0"]



def _digest(text: str) -> str:
    """A short, stable, non-cryptographic id. Never used for security.

    `usedforsecurity=False` is not a performance hint -- it is the declaration
    that this digest authenticates nothing, which is also what lets the build
    run on a FIPS-enforcing host where SHA-1 is otherwise unavailable.
    """
    return hashlib.sha1(text.encode(), usedforsecurity=False).hexdigest()

def parse_version(text: str) -> Tuple[int, int, int]:
    parts = re.findall(r"\d+", str(text).lstrip("v"))
    parts += ["0"] * (3 - len(parts))
    return tuple(int(p) for p in parts[:3])            # type: ignore[return-value]


def minor(text: str) -> Tuple[int, int]:
    major, minor_, _ = parse_version(text)
    return major, minor_


def next_release(current: str) -> Optional[str]:
    current_minor = minor(current)
    for release in RELEASES:
        if minor(release) > current_minor:
            return release
    return None


def node_version(node: dict) -> str:
    return str(deep_get(node, "status.nodeInfo.kubeletVersion", "v1.30.2")).lstrip("v")


def set_node_version(node: dict, version: str) -> None:
    node.setdefault("status", {}).setdefault("nodeInfo", {})["kubeletVersion"] = \
        f"v{version.lstrip('v')}"


def skew_ok(control_plane: str, kubelet: str) -> bool:
    """kubelet may be up to 3 minor versions behind the API server, never ahead."""
    cp_major, cp_minor = minor(control_plane)
    k_major, k_minor = minor(kubelet)
    if (k_major, k_minor) > (cp_major, cp_minor):
        return False
    return (cp_major, cp_minor) <= (k_major, k_minor + 3)


# --------------------------------------------------------------------------
# kubeadm
# --------------------------------------------------------------------------
def kubeadm(cluster: Cluster, args: List[str], flags: Dict[str, Any]) -> Tuple[bool, str]:
    if not args:
        return True, KUBEADM_HELP
    action = args[0]

    if action == "version":
        return True, (f"kubeadm version: &version.Info{{Major:\"{minor(cluster.version)[0]}\", "
                      f"Minor:\"{minor(cluster.version)[1]}\", "
                      f"GitVersion:\"v{cluster.version}\"}}")

    if action == "token":
        sub = args[1] if len(args) > 1 else "list"
        # Cosmetic only: a fake kubeadm join token so the output looks real.
        # usedforsecurity=False says so explicitly -- this is not authenticating
        # anything, and no real token is ever generated by this program.
        token = (_digest(f"{cluster.tick}")[:6] + "." +
                 _digest(f"{cluster.tick}x")[:16])
        if sub == "create":
            if flags.get("--print-join-command"):
                return True, (f"kubeadm join 172.18.0.2:6443 --token {token} "
                              f"--discovery-token-ca-cert-hash sha256:"
                              f"{hashlib.sha256(cluster.name.encode()).hexdigest()}")
            return True, token
        return True, ("TOKEN                     TTL         USAGES\n"
                      f"{token}   23h         authentication,signing")

    if action == "join":
        name = flags.get("--node-name") or f"lab-worker-{len(cluster.list('Node'))}"
        if cluster.get("Node", "", name):
            return False, f'node "{name}" already exists in the cluster'
        if not any(a.startswith("--token") or a == "--token" for a in args + list(flags)):
            return False, ("a bootstrap token is required: run `kubeadm token create "
                           "--print-join-command` on the control plane first")
        node = add_node(cluster, name)
        set_node_version(node, cluster.version)
        cluster.record("Normal", "NodeJoined",
                       f"Node {name} joined the cluster via kubeadm",
                       f"node/{name}", "default")
        return True, ("[preflight] Running pre-flight checks\n"
                      "[kubelet-start] Starting the kubelet\n"
                      "[tls-bootstrap] Waiting for the kubelet to perform the TLS "
                      "bootstrap\n\n"
                      f"This node has joined the cluster: {name}\n"
                      "Run 'kubectl get nodes' on the control plane to see it.")

    if action == "upgrade":
        return _kubeadm_upgrade(cluster, args[1:], flags)

    if action == "certs":
        return _kubeadm_certs(cluster, args[1:], flags)

    if action == "init":
        return False, ("this cluster is already initialised. `kubeadm init` builds a "
                       "control plane from scratch on a real machine -- practise it "
                       "on kind/minikube. Here, start from `kubeadm upgrade plan`.")

    if action == "reset":
        return False, "refusing to reset the lab control plane (use `sim reset`)"

    return False, f"unknown kubeadm command: {action}"


def _kubeadm_upgrade(cluster: Cluster, args: List[str],
                     flags: Dict[str, Any]) -> Tuple[bool, str]:
    sub = args[0] if args else "plan"
    control_plane = cluster.version
    target = next_release(control_plane)

    if sub == "plan":
        lines = ["[upgrade/config] Reading configuration from the cluster...",
                 "",
                 "Components that must be upgraded manually after you have upgraded "
                 "the control plane with 'kubeadm upgrade apply':",
                 "COMPONENT   CURRENT             TARGET"]
        counts: Dict[str, int] = {}
        for node in cluster.list("Node"):
            counts[node_version(node)] = counts.get(node_version(node), 0) + 1
        for version, count in sorted(counts.items()):
            lines.append(f"kubelet     {count} x v{version:<12}   "
                         f"v{target or control_plane}")
        lines += ["", "Upgrade to the latest stable version:", "",
                  "COMPONENT                 CURRENT   TARGET",
                  f"kube-apiserver            v{control_plane}   v{target or control_plane}",
                  f"kube-controller-manager   v{control_plane}   v{target or control_plane}",
                  f"kube-scheduler            v{control_plane}   v{target or control_plane}",
                  f"kubeadm                   v{control_plane}   v{target or control_plane}",
                  ""]
        if target:
            lines += ["You can now apply the upgrade by executing the following:", "",
                      f"    kubeadm upgrade apply v{target}", "",
                      "Then, on EACH node: kubectl drain <node> --ignore-daemonsets, "
                      "kubeadm upgrade node, kubectl uncordon <node>."]
        else:
            lines.append("Your cluster is already at the newest version this lab knows.")
        return True, "\n".join(lines)

    if sub == "apply":
        wanted = next((a for a in args[1:] if a.startswith("v") or a[0].isdigit()), "")
        if not wanted:
            return False, "usage: kubeadm upgrade apply v<version>"
        wanted = wanted.lstrip("v")
        if wanted not in RELEASES:
            return False, (f"version v{wanted} is not available. Known releases: "
                           + ", ".join("v" + r for r in RELEASES))
        current_minor, target_minor = minor(control_plane), minor(wanted)
        if target_minor < current_minor:
            return False, (f"downgrades are not supported: cluster is v{control_plane}")
        if target_minor[1] - current_minor[1] > 1 or target_minor[0] != current_minor[0]:
            return False, (f"you cannot skip minor versions: upgrade v{control_plane} "
                           f"-> v{next_release(control_plane)} first, one minor at a time")
        cluster.version = wanted
        control = next((n for n in cluster.list("Node")
                        if deep_get(n, "status.role") == "control-plane"), None)
        if control is not None:
            set_node_version(control, wanted)
        cluster.record("Normal", "ControlPlaneUpgraded",
                       f"Control plane upgraded to v{wanted}", "cluster", "default")
        return True, ("[upgrade/config] Reading configuration from the cluster...\n"
                      "[upgrade/versions] Cluster version: v" + control_plane + "\n"
                      f"[upgrade/apply] Upgrading to version v{wanted}\n"
                      "[upgrade/staticpods] Upgrading kube-apiserver, "
                      "kube-controller-manager, kube-scheduler, etcd\n\n"
                      f"[upgrade/successful] SUCCESS! Your cluster was upgraded to "
                      f"\"v{wanted}\".\n\n"
                      "Now upgrade the kubelet on each node:\n"
                      "  kubectl drain <node> --ignore-daemonsets\n"
                      "  kubeadm upgrade node --node <node>\n"
                      "  kubectl uncordon <node>")

    if sub == "node":
        name = flags.get("--node")
        if not isinstance(name, str):
            name = args[1] if len(args) > 1 else ""
        if not name:
            return False, ("usage: kubeadm upgrade node --node <name>\n"
                           "(on a real cluster you run this ON the node; here you name it)")
        node = cluster.get("Node", "", name)
        if node is None:
            return False, f'nodes "{name}" not found'
        if minor(node_version(node)) == minor(cluster.version):
            return True, f"[upgrade] node {name} is already at v{cluster.version}"
        if minor(node_version(node)) > minor(cluster.version):
            return False, (f"node {name} is newer than the control plane -- upgrade "
                           "the control plane first with `kubeadm upgrade apply`")
        if not deep_get(node, "spec.unschedulable", False):
            return False, (f"node {name} is still schedulable. Drain it first:\n"
                           f"  kubectl drain {name} --ignore-daemonsets")
        set_node_version(node, cluster.version)
        cluster.record("Normal", "NodeUpgraded",
                       f"kubelet on {name} upgraded to v{cluster.version}",
                       f"node/{name}", "default")
        return True, (f"[upgrade] Upgrading kubelet configuration on {name}\n"
                      f"[upgrade] The kubelet on {name} is now v{cluster.version}\n"
                      f"Remember: kubectl uncordon {name}")

    return False, f"unknown kubeadm upgrade command: {sub}"


def _kubeadm_certs(cluster: Cluster, args: List[str],
                   flags: Dict[str, Any]) -> Tuple[bool, str]:
    sub = args[0] if args else "check-expiration"
    if sub == "check-expiration":
        rows = ["CERTIFICATE                EXPIRES(days)   RESIDUAL   EXTERNALLY MANAGED"]
        for name, days in sorted(cluster.pki.items()):
            state = "no"
            rows.append(f"{name:<26} {days:<15} "
                        f"{'OK' if days > 30 else 'EXPIRING SOON':<10} {state}")
        rows.append("")
        rows.append("Certificates are renewed automatically by `kubeadm upgrade apply`, "
                    "or manually with `kubeadm certs renew all`.")
        return True, "\n".join(rows)
    if sub == "renew":
        what = args[1] if len(args) > 1 else "all"
        renewed = list(cluster.pki) if what == "all" else [what]
        for name in renewed:
            if name in cluster.pki:
                cluster.pki[name] = 364 if name != "ca" else 3650
        return True, ("certificate renewed: " + ", ".join(renewed) +
                      "\n\nRestart kube-apiserver, kube-controller-manager and "
                      "kube-scheduler for the new certificates to take effect.")
    return False, f"unknown kubeadm certs command: {sub}"


def age_certificates(cluster: Cluster, days: int = 1) -> None:
    for name in list(cluster.pki):
        cluster.pki[name] = max(0, cluster.pki[name] - days)
    for user in cluster.kubeconfig.get("users", {}).values():
        if "expires_in_days" in user:
            user["expires_in_days"] = max(0, user["expires_in_days"] - days)


# --------------------------------------------------------------------------
# etcdctl
# --------------------------------------------------------------------------
REQUIRED_ETCD_FLAGS = ("--endpoints", "--cacert", "--cert", "--key")


def etcdctl(cluster: Cluster, args: List[str], flags: Dict[str, Any],
            env: Dict[str, str], base_dir: str) -> Tuple[bool, str]:
    if env.get("ETCDCTL_API") not in (None, "3"):
        return False, "this lab only speaks the v3 API: set ETCDCTL_API=3"
    if not args:
        return True, ETCDCTL_HELP
    action = args[0]

    if action == "member":
        return True, ("ID          STATUS    NAME                 PEER ADDRS"
                      "               CLIENT ADDRS\n"
                      "8e9e05c52164694d, started, lab-control-plane, "
                      "https://172.18.0.2:2380, https://172.18.0.2:2379")

    if action == "endpoint":
        return True, ("https://127.0.0.1:2379, 8e9e05c52164694d, 3.5.12, "
                      f"{max(1, len(cluster.all_objects()) // 4)} MB, true, false, "
                      f"{cluster.tick}, {cluster.tick}, {cluster.tick}")

    if action != "snapshot":
        return False, f"unknown etcdctl command: {action}"

    sub = args[1] if len(args) > 1 else ""
    path = args[2] if len(args) > 2 else flags.get("--data-dir", "")

    if sub in ("save", "restore"):
        missing = [f for f in REQUIRED_ETCD_FLAGS if f not in flags]
        if sub == "restore":
            missing = [f for f in missing if f != "--endpoints"]
        if missing:
            return False, ("Error: rpc error: code = Unavailable desc = "
                           "transport is closing\n\n"
                           "(you are missing " + ", ".join(missing) + ". Every "
                           "etcdctl call against a kubeadm cluster needs\n"
                           "  --endpoints=https://127.0.0.1:2379 \\\n"
                           "  --cacert=/etc/kubernetes/pki/etcd/ca.crt \\\n"
                           "  --cert=/etc/kubernetes/pki/etcd/server.crt \\\n"
                           "  --key=/etc/kubernetes/pki/etcd/server.key)")

    if sub == "save":
        if not path:
            return False, "usage: etcdctl snapshot save <file> [flags]"
        snapshot = cluster.snapshot()
        snapshot["version"] = cluster.version
        snapshot["taken_at_tick"] = cluster.tick
        payload = json.dumps(snapshot, default=str)
        cluster.etcd_snapshots[path] = {
            "data": snapshot,
            "revision": cluster.tick,
            "keys": len(cluster.all_objects()),
            "size": len(payload),
            "hash": hashlib.sha256(payload.encode()).hexdigest()[:8],
        }
        _write_side_file(base_dir, path, payload)
        return True, (f"{{\"level\":\"info\",\"msg\":\"fetching snapshot\"}}\n"
                      f"{{\"level\":\"info\",\"msg\":\"fetched snapshot\","
                      f"\"path\":\"{path}\"}}\n"
                      f"Snapshot saved at {path}")

    if sub == "status":
        if path not in cluster.etcd_snapshots:
            return False, f"stat {path}: no such file or directory"
        meta = cluster.etcd_snapshots[path]
        return True, ("HASH       REVISION   TOTAL KEYS   TOTAL SIZE\n"
                      f"{meta['hash']}   {meta['revision']:<10} {meta['keys']:<12} "
                      f"{meta['size'] // 1024 + 1} kB")

    if sub == "restore":
        if path not in cluster.etcd_snapshots:
            return False, (f"stat {path}: no such file or directory\n"
                           "(take one first: etcdctl snapshot save <file> …)")
        snapshot = cluster.etcd_snapshots[path]["data"]
        cluster.objects.clear()
        for obj in snapshot["objects"]:
            cluster.put(obj)
        cluster.tick = int(snapshot.get("tick", cluster.tick))
        cluster.load = dict(snapshot.get("load", {}))
        cluster.chaos = dict(snapshot.get("chaos", {}))
        cluster.record("Warning", "EtcdRestored",
                       f"etcd restored from {path} (revision "
                       f"{snapshot.get('taken_at_tick')})", "cluster", "default")
        return True, (f"{{\"level\":\"info\",\"msg\":\"restoring snapshot\","
                      f"\"path\":\"{path}\"}}\n"
                      f"{{\"level\":\"info\",\"msg\":\"restored snapshot\"}}\n\n"
                      f"Restored {len(snapshot['objects'])} objects "
                      f"(revision {snapshot.get('taken_at_tick')}).\n"
                      "On a real cluster you would now point the etcd static pod at "
                      "the new --data-dir and let the API server restart.")

    return False, f"unknown etcdctl snapshot command: {sub}"


def _write_side_file(base_dir: str, path: str, payload: str) -> None:
    """Also drop the snapshot on disk when the path is writable."""
    try:
        target = path if os.path.isabs(path) else os.path.join(base_dir, path)
        if os.path.isabs(path) and not os.path.isdir(os.path.dirname(target)):
            return
        os.makedirs(os.path.dirname(target) or ".", exist_ok=True)
        with open(target, "w", encoding="utf-8") as handle:
            handle.write(payload)
    except OSError:
        pass


# --------------------------------------------------------------------------
# certificates + kubeconfig
# --------------------------------------------------------------------------
def make_csr(cluster: Cluster, name: str, user: str, groups: List[str]) -> dict:
    return {
        "apiVersion": "certificates.k8s.io/v1",
        "kind": "CertificateSigningRequest",
        "metadata": {"name": name, "uid": cluster.next_uid(),
                     "creationTick": cluster.tick, "labels": {}, "annotations": {}},
        "spec": {"request": "<base64 PEM CSR>", "signerName":
                 "kubernetes.io/kube-apiserver-client",
                 "username": user, "groups": groups or ["system:authenticated"],
                 "usages": ["client auth"], "expirationSeconds": 86400},
        "status": {"phase": "Pending"},
    }


def certificate(cluster: Cluster, args: List[str]) -> Tuple[bool, str]:
    """kubectl certificate approve|deny <name>"""
    if len(args) < 2:
        return False, "usage: kubectl certificate approve|deny <csr-name>"
    action, name = args[0], args[1]
    csr = cluster.get("CertificateSigningRequest", "", name)
    if csr is None:
        return False, f'certificatesigningrequests "{name}" not found'
    if action == "approve":
        csr.setdefault("status", {}).update({
            "phase": "Approved,Issued",
            "conditions": [{"type": "Approved", "status": "True",
                            "reason": "KubectlApprove"}],
            "certificate": "<base64 PEM certificate>"})
        user = deep_get(csr, "spec.username")
        cluster.kubeconfig.setdefault("users", {})[user] = {
            "client-certificate": f"{user}.crt", "client-key": f"{user}.key",
            "groups": deep_get(csr, "spec.groups", []) or [], "expires_in_days": 1}
        cluster.record("Normal", "CSRApproved", f"CSR {name} approved and issued",
                       f"certificatesigningrequest/{name}", "default")
        return True, (f"certificatesigningrequest.certificates.k8s.io/{name} approved\n"
                      f"\nExtract the certificate with:\n"
                      f"  kubectl get csr {name} -o jsonpath='{{.status.certificate}}' "
                      "| base64 -d > " + f"{user}.crt")
    if action == "deny":
        csr.setdefault("status", {}).update({
            "phase": "Denied",
            "conditions": [{"type": "Denied", "status": "True"}]})
        return True, f"certificatesigningrequest.certificates.k8s.io/{name} denied"
    return False, f"unknown certificate action: {action}"


def kubeconfig_command(cluster: Cluster, args: List[str],
                       flags: Dict[str, Any]) -> Tuple[bool, str]:
    """The kubeconfig half of `kubectl config`."""
    action = args[0]
    config = cluster.kubeconfig

    if action == "set-credentials":
        user = args[1] if len(args) > 1 else ""
        if not user:
            return False, "usage: kubectl config set-credentials <user> [flags]"
        entry = config.setdefault("users", {}).setdefault(user, {})
        for flag, key in (("--client-certificate", "client-certificate"),
                          ("--client-key", "client-key"),
                          ("--token", "token")):
            if flags.get(flag):
                entry[key] = flags[flag]
        entry.setdefault("expires_in_days", 1)
        return True, f'User "{user}" set.'

    if action == "set-cluster":
        name = args[1] if len(args) > 1 else ""
        config.setdefault("clusters", {})[name] = {
            "server": flags.get("--server", "https://127.0.0.1:6443"),
            "certificate-authority": flags.get("--certificate-authority", "ca.crt")}
        return True, f'Cluster "{name}" set.'

    if action == "set-context":
        name = args[1] if len(args) > 1 else "--current"
        if name == "--current" or flags.get("--current"):
            name = config.get("current-context", "lab")
        entry = config.setdefault("contexts", {}).setdefault(
            name, {"cluster": "lab-cluster", "user": "admin", "namespace": "default"})
        for flag, key in (("--cluster", "cluster"), ("--user", "user"),
                          ("--namespace", "namespace")):
            if flags.get(flag):
                entry[key] = flags[flag]
        if flags.get("--namespace"):
            namespace = flags["--namespace"]
            if not cluster.get("Namespace", "", namespace):
                return False, f'namespace "{namespace}" not found'
            if name == config.get("current-context"):
                cluster.current_namespace = namespace
        return True, f'Context "{name}" modified.'

    if action == "use-context":
        name = args[1] if len(args) > 1 else ""
        if name not in config.get("contexts", {}):
            return False, (f'no context exists with the name: "{name}"\n'
                           "create one first: kubectl config set-context "
                           f"{name} --cluster=lab-cluster --user=<user>")
        config["current-context"] = name
        context = config["contexts"][name]
        cluster.current_user = context.get("user", "admin")
        cluster.current_namespace = context.get("namespace", "default")
        return True, f'Switched to context "{name}".'

    if action == "get-contexts":
        rows = ["CURRENT   NAME       CLUSTER       AUTHINFO   NAMESPACE"]
        for name, context in config.get("contexts", {}).items():
            mark = "*" if name == config.get("current-context") else " "
            rows.append(f"{mark:<9} {name:<10} {context.get('cluster', ''):<13} "
                        f"{context.get('user', ''):<10} {context.get('namespace', '')}")
        return True, "\n".join(rows)

    if action == "get-users":
        return True, "NAME\n" + "\n".join(config.get("users", {}))

    if action == "current-context":
        return True, config.get("current-context", "lab")

    if action == "view":
        from . import miniyaml
        return True, miniyaml.dump({
            "apiVersion": "v1", "kind": "Config",
            "current-context": config.get("current-context"),
            "clusters": [{"name": n, "cluster": c}
                         for n, c in config.get("clusters", {}).items()],
            "users": [{"name": n,
                       "user": {k: v for k, v in u.items()
                                if k not in ("groups", "expires_in_days")}}
                      for n, u in config.get("users", {}).items()],
            "contexts": [{"name": n, "context": c}
                         for n, c in config.get("contexts", {}).items()]})
    return False, f"unknown config action: {action}"


# --------------------------------------------------------------------------
# container registry
# --------------------------------------------------------------------------
PUBLIC_IMAGES = (
    "nginx", "busybox", "postgres", "redis", "alpine", "python", "node", "mysql",
    "mongo", "httpd", "traefik", "prom/node-exporter", "fluent/fluent-bit",
    "registry.k8s.io/ingress-nginx/controller", "hashicorp/http-echo",
    "grafana/grafana", "prom/prometheus", "quay.io/prometheus/alertmanager",
    # images the labs themselves ship -- they must pull, or the lesson is wrong
    "lab.example.com/backup-operator",
)


def image_known(cluster: Cluster, image: str) -> Tuple[bool, bool]:
    """(pullable by a node, private) for an image reference.

    Built locally but never pushed == not pullable: a kubelet fetches over the
    network and cannot reach your workstation.
    """
    reference = str(image)
    for candidate in (reference, reference.rsplit(":", 1)[0]):
        meta = cluster.registry.get(candidate)
        if meta is not None:
            return bool(meta.get("pushed")), bool(meta.get("private"))
    repository = reference.rsplit(":", 1)[0]
    for known in PUBLIC_IMAGES:
        if repository == known or repository.endswith("/" + known):
            return True, False
    return False, False


def docker(cluster: Cluster, args: List[str], flags: Dict[str, Any]) -> Tuple[bool, str]:
    """A tiny local registry so image pulls can succeed, fail or need credentials."""
    if not args:
        return True, DOCKER_HELP
    action = args[0]

    if action == "build":
        tag = flags.get("-t") or flags.get("--tag")
        if not tag:
            return False, 'usage: docker build -t <name>:<tag> .'
        digest = "sha256:" + hashlib.sha256(f"{tag}{cluster.tick}".encode()).hexdigest()[:12]
        cluster.registry[tag] = {"private": False, "digest": digest, "built": True,
                                 "pushed": False}
        return True, (f"[+] Building 2.4s (7/7) FINISHED\n"
                      f" => exporting to image\n"
                      f" => => naming to docker.io/library/{tag}\n"
                      f" => => writing image {digest}\n\n"
                      f"Built {tag}. It exists on this machine only until you push it -- "
                      "a Kubernetes node cannot pull from your laptop.")

    if action == "tag":
        if len(args) < 3:
            return False, "usage: docker tag <source> <target>"
        source, target = args[1], args[2]
        if source not in cluster.registry:
            exists, _ = image_known(cluster, source)
            if not exists:
                return False, f"Error response from daemon: No such image: {source}"
        cluster.registry[target] = dict(cluster.registry.get(source, {"digest": "sha256:public"}))
        cluster.registry[target]["pushed"] = False
        return True, ""

    if action == "push":
        reference = args[1] if len(args) > 1 else ""
        if reference not in cluster.registry:
            return False, (f"An image does not exist locally with the tag: {reference}\n"
                           "build or tag it first")
        private = "private" in reference or bool(flags.get("--private"))
        cluster.registry[reference].update({"pushed": True, "private": private})
        return True, (f"The push refers to repository [{reference.rsplit(':', 1)[0]}]\n"
                      f"latest: digest: {cluster.registry[reference]['digest']} size: 1571\n"
                      + ("\nThis repository is PRIVATE: pods need an imagePullSecret "
                         "(kubectl create secret docker-registry ...)." if private else ""))

    if action == "images":
        rows = ["REPOSITORY                          TAG        DIGEST          "
                "PUSHED   PRIVATE"]
        for reference, meta in sorted(cluster.registry.items()):
            repository, _, tag = reference.partition(":")
            rows.append(f"{repository:<35} {tag or 'latest':<10} "
                        f"{meta.get('digest', '')[:14]:<15} "
                        f"{str(meta.get('pushed', False)):<8} "
                        f"{meta.get('private', False)}")
        if len(rows) == 1:
            rows.append("(nothing built yet -- try: docker build -t myapp:1.0 .)")
        return True, "\n".join(rows)

    if action == "rmi":
        reference = args[1] if len(args) > 1 else ""
        cluster.registry.pop(reference, None)
        return True, f"Untagged: {reference}"

    return False, (f"unknown docker command: {action}\n"
                   "This lab models a registry, not a real Docker daemon: build, tag, "
                   "push, images, rmi.")


KUBEADM_HELP = """kubeadm -- cluster lifecycle (simulated)

  kubeadm version
  kubeadm token create --print-join-command
  kubeadm join <endpoint> --token <t> --node-name lab-worker-4
  kubeadm upgrade plan
  kubeadm upgrade apply v1.31.1
  kubeadm upgrade node --node lab-worker-1     (drain it first)
  kubeadm certs check-expiration
  kubeadm certs renew all

The version-skew and ordering rules are enforced, because that is what the exam
and a real upgrade night actually test."""

ETCDCTL_HELP = """etcdctl -- etcd v3 client (simulated)

  ETCDCTL_API=3 etcdctl member list --endpoints=... --cacert=... --cert=... --key=...
  ETCDCTL_API=3 etcdctl snapshot save /backup/etcd.db <the four flags>
  ETCDCTL_API=3 etcdctl snapshot status /backup/etcd.db <the four flags>
  ETCDCTL_API=3 etcdctl snapshot restore /backup/etcd.db --data-dir=/var/lib/etcd-new

The four TLS flags are required, exactly as on a kubeadm cluster."""

DOCKER_HELP = """docker -- image + registry model (simulated)

  docker build -t myapp:1.0 .
  docker tag myapp:1.0 registry.lab/private/myapp:1.0
  docker push registry.lab/private/myapp:1.0
  docker images

Only the Kubernetes-facing half is modelled: whether an image can be pulled, and
whether it needs an imagePullSecret. Real Dockerfile builds need a real daemon."""
